<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Stable Isotope Trajectory Analysis (SITA) • ecotraj</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Stable Isotope Trajectory Analysis (SITA)">
<meta property="og:description" content="ecotraj">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">ecotraj</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/IntroductionETA.html">Introduction to Ecological Trajectory Analysis</a>
    </li>
    <li>
      <a href="../articles/SITA.html">Stable Isotope Trajectory Analysis (SITA)</a>
    </li>
    <li>
      <a href="../articles/Transformation.html">Transformation of dissimilarities in community data</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="SITA_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Stable Isotope Trajectory Analysis (SITA)</h1>
                        <h4 class="author">Anthony STURBOIS</h4>
            
            <h4 class="date">2021-08-26</h4>
      
      
      <div class="hidden name"><code>SITA.Rmd</code></div>

    </div>

    
    
<div id="about-this-vignette" class="section level2">
<h2 class="hasAnchor">
<a href="#about-this-vignette" class="anchor"></a>1. About this vignette</h2>
<p>This vignette present some ecological applications used by Sturbois at al. (under review) in the new stable isotope trajectory analysis framework. Example datasets have been included in the package for reproducibility. After the calculation of the necessary distance- and direction-based metrics, the vignette focuses, for each ecological applications, on the creation of trajectory charts.</p>
</div>
<div id="loading-libraries" class="section level2">
<h2 class="hasAnchor">
<a href="#loading-libraries" class="anchor"></a>2. Loading libraries</h2>
<p>First of all, we load the required libraries, including <code>ecotraj</code>:</p>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## Loading required package: sp</code></pre>
<pre><code>## rgdal: version: 1.5-23, (SVN revision 1121)
## Geospatial Data Abstraction Library extensions to R successfully loaded
## Loaded GDAL runtime: GDAL 3.2.1, released 2020/12/29
## Path to GDAL shared files: /Users/runner/work/_temp/Library/rgdal/gdal
## GDAL binary built with GEOS: TRUE 
## Loaded PROJ runtime: Rel. 7.2.1, January 1st, 2021, [PJ_VERSION: 721]
## Path to PROJ shared files: /Users/runner/work/_temp/Library/rgdal/proj
## PROJ CDN enabled: FALSE
## Linking to sp version:1.4-5
## To mute warnings of possible GDAL/OSR exportToProj4() degradation,
## use options("rgdal_show_exportToProj4_warnings"="none") before loading rgdal.
## Overwritten PROJ_LIB was /Users/runner/work/_temp/Library/rgdal/proj</code></pre>
<pre><code>## 
## Attaching package: 'plyr'</code></pre>
<pre><code>## The following objects are masked from 'package:reshape':
## 
##     rename, round_any</code></pre>
<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following objects are masked from 'package:plyr':
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize</code></pre>
<pre><code>## The following object is masked from 'package:gridExtra':
## 
##     combine</code></pre>
<pre><code>## The following object is masked from 'package:reshape':
## 
##     rename</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre><code>## NOTE: Either Arial Narrow or Roboto Condensed fonts are required to use these themes.</code></pre>
<pre><code>##       Please use hrbrthemes::import_roboto_condensed() to install Roboto Condensed and</code></pre>
<pre><code>##       if Arial Narrow is not on your system, please see https://bit.ly/arialnarrow</code></pre>
<pre><code>## Loading required package: viridisLite</code></pre>
<pre><code>## 
## Attaching package: 'viridis'</code></pre>
<pre><code>## The following object is masked from 'package:scales':
## 
##     viridis_pal</code></pre>
</div>
<div id="spatial-and-temporal-resource-partitioning-in-fur-seals" class="section level2">
<h2 class="hasAnchor">
<a href="#spatial-and-temporal-resource-partitioning-in-fur-seals" class="anchor"></a>3. Spatial and temporal resource partitioning in fur seals</h2>
<div id="fur-seal-stable-isotope-dataset" class="section level3">
<h3 class="hasAnchor">
<a href="#fur-seal-stable-isotope-dataset" class="anchor"></a>3.1 Fur seal stable isotope dataset</h3>
<p>We begin by loading the package dataset <code>furseals</code>:</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"furseals"</span><span class="op">)</span></code></pre></div>
<p>This is a subset of the dataset provided in:</p>
<ul>
<li>Kernaléguen, L., Arnould, J.P.Y., Guinet, C., Cherel, Y., 2015. Determinants of individual foraging specialization in large marine vertebrates, the Antarctic and subantarctic fur seals. <em>Journal of Animal Ecology</em> 1081–1091.</li>
</ul>
<p>Briefly, fur seals [the Antarctic fur seal <em>Arctocephalus gazella</em> (AFS) and subantarctic fur seal <em>A. tropicalis</em> (SAFS)] whisker SI values yield unique long-term information on individual behaviour which integrates the spatial, trophic and temporal dimensions of the ecological niche. The foraging strategies of this two species of sympatric fur seals were examined in the winter 2001/2002 at Crozet, Amsterdam and Kerguelen Islands (Southern Ocean) using the stable isotope values of serially sampled whiskers. The method consists in the analysis of consecutive whisker sections (3 mm long) starting from the proximal (facial) end, with the most recently synthesized tissue remaining under the skin. Only individuals (n = 47) with whiskers totalizing at least 30 sections were selected in the initial data, and only those 30 sections were considered herein, from t1 (more recent values) to t30 (oldest values).</p>
</div>
<div id="trajectory-metrics" class="section level3">
<h3 class="hasAnchor">
<a href="#trajectory-metrics" class="anchor"></a>3.2 Trajectory metrics</h3>
<p>In this section, we illustrate how to calculate trajectory metrics to characterize the foraging strategy of each fur seal. In the following sections, we show how to use these metrics as data to create plots.</p>
<p>First, we calculate net changes relative to the initial state (i.e. the distance between stable isotope compositions (i.e state) of each whisker section and the initial stable isotope composition):</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Net_changes</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryLengths2D</a></span><span class="op">(</span><span class="va">furseals</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"d13C"</span>,<span class="st">"d15N"</span><span class="op">)</span><span class="op">]</span>,
                                 <span class="va">furseals</span><span class="op">$</span><span class="va">ID_SITA</span>,
                                 <span class="va">furseals</span><span class="op">$</span><span class="va">Time</span>, relativeToInitial<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span> 
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">Net_changes</span><span class="op">)</span></code></pre></div>
<pre><code>##       Lt1_t2    Lt1_t3    Lt1_t4    Lt1_t5     Lt1_t6    Lt1_t7    Lt1_t8
## 1 0.08246211 1.0892314 2.0775851 2.3714985 2.20626585 1.7839633 1.6819920
## 2 0.59304131 0.9583074 0.8218643 0.2677928 0.08105554 0.7460168 0.4970191
## 3 0.23256182 1.4622975 3.0029069 2.8817373 2.55906428 1.6445066 1.6734124
## 4 1.24068086 2.1744498 2.3520872 2.4028260 2.28455422 2.2679323 0.9493714
## 5 1.80624915 3.0818595 3.8011940 4.4793800 4.50949775 4.3885128 2.9507619
## 6 1.13903687 4.3444610 4.0299700 6.4151503 5.96779901 6.0314152 7.2216151
##     Lt1_t9   Lt1_t10   Lt1_t11   Lt1_t12   Lt1_t13   Lt1_t14   Lt1_t15
## 1 1.344206 1.2735702 1.0631895 0.7915611 0.8486489 1.0500638 1.1961910
## 2 1.092157 0.6772156 0.7744366 0.2702240 0.6136685 1.0261861 0.7000864
## 3 2.518128 2.0782324 1.7294097 1.1594387 1.7649975 2.7768920 2.4641059
## 4 0.577084 0.6049504 0.5920490 1.5973206 1.1985112 0.8119858 0.6936173
## 5 2.187465 0.9662236 2.6143697 2.7163971 2.7958673 2.6837384 2.2504011
## 6 7.173525 6.2867554 0.2478810 0.9972668 0.9076795 0.5088025 0.6640821
##     Lt1_t16   Lt1_t17   Lt1_t18   Lt1_t19  Lt1_t20  Lt1_t21   Lt1_t22   Lt1_t23
## 1 1.5432880 1.6484832 1.6042908 1.6566572 1.108358 0.381577 0.3006742 1.4772136
## 2 0.5592397 0.4460235 0.6495922 0.7966461 1.787011 1.591433 1.5776276 1.6305889
## 3 0.2755014 0.4497755 0.6170292 0.2879392 1.103359 2.145421 2.1758332 2.1139858
## 4 0.3626927 0.7276160 0.9288983 0.7955941 2.352899 1.851222 2.2158782 2.3341939
## 5 1.8418754 1.8304906 1.8207087 1.5938494 1.553721 1.583789 1.5700115 0.6566011
## 6 3.6309179 4.0313501 6.0026223 6.9996921 6.341455 7.297884 7.5324814 6.1068566
##     Lt1_t24   Lt1_t25   Lt1_t26   Lt1_t27    Lt1_t28   Lt1_t29   Lt1_t30
## 1 1.5890755 1.0783103 1.1172381 2.0638181 2.52046504 2.2934779 1.6320787
## 2 0.2046069 0.3937309 0.3849480 0.7032112 0.89491061 0.3901513 0.7480241
## 3 2.2036883 1.8413856 1.6354464 1.9473328 1.59052601 1.3147125 1.6315076
## 4 2.1019596 0.2814321 0.4237924 0.7473988 0.05360037 0.3889730 0.7375269
## 5 4.0823528 4.4187248 4.3025323 4.3520214 3.43035873 0.7908375 1.2435373
## 6 1.7282780 2.1873694 1.2698965 0.5391030 0.40993902 0.4085156 0.7709643
##   Trajectory
## 1   40.87543
## 2   21.87682
## 3   49.28114
## 4   36.05110
## 5   76.30333
## 6  107.19276</code></pre>
<p>We then calculate trajectory segment lengths, i.e. the distance between the stable isotope composition of consecutive whisker sections in the stable isotope space:</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Segment_lengths</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryLengths2D</a></span><span class="op">(</span><span class="va">furseals</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"d13C"</span>,<span class="st">"d15N"</span><span class="op">)</span><span class="op">]</span>,
                                     <span class="va">furseals</span><span class="op">$</span><span class="va">ID_SITA</span>,
                                     <span class="va">furseals</span><span class="op">$</span><span class="va">Time</span>, relativeToInitial<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span> 
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">Segment_lengths</span><span class="op">)</span></code></pre></div>
<pre><code>##           S1        S2       S3         S4         S5         S6        S7
## 1 0.08246211 1.0799190 1.109759 0.39708060 0.16604819 0.69542793 0.1332817
## 2 0.59304131 0.4019664 0.165463 0.62878295 0.24977790 0.81093588 0.4377728
## 3 0.23256182 1.2719328 1.561554 0.13206059 0.81044432 1.21893232 0.3748826
## 4 1.24068086 0.9337907 0.177792 0.08732125 0.11957006 0.06462971 1.3506817
## 5 1.80624915 1.2835334 1.452408 1.22947021 0.05423099 0.33640006 1.4518034
## 6 1.13903687 3.2697465 1.007842 2.40400083 1.02618176 0.80004000 1.4924584
##           S8         S9       S10       S11        S12       S13       S14
## 1 0.35206960 0.13800362 0.2119929 0.3940774 0.08004998 0.2026154 0.2040221
## 2 0.94680304 0.44818858 0.6290191 0.5362695 0.52697249 0.4552637 0.3411231
## 3 1.04072379 0.44107256 0.3592548 0.7240691 0.66598649 1.0131856 0.4798427
## 4 1.44655867 0.09009439 1.1117198 2.1338287 0.39901128 1.4341130 0.3064376
## 5 0.78147681 1.29231962 3.5747035 0.6261150 0.09265528 0.2502838 0.6440194
## 6 0.05115662 0.88680381 6.3555849 0.9913889 0.09047099 0.4029814 1.1639300
##         S15       S16       S17       S18       S19       S20        S21
## 1 0.3703039 0.1632330 1.7046178 1.0355916 1.0132186 0.7423544 0.11970798
## 2 0.1554670 0.2837781 0.2257632 0.6603492 0.9904383 0.5893293 0.03956008
## 3 2.3198028 0.5979908 0.3078262 0.3993219 1.3487198 1.1301832 0.04002499
## 4 0.8420291 0.4612776 1.5254799 0.1874727 1.5712829 0.5036268 0.41386471
## 5 0.4404407 0.5163768 0.5204652 0.2380084 0.1802276 0.2205108 0.22402009
## 6 2.9863858 0.7196339 1.9833855 1.0789699 0.7247068 0.9616637 0.24162988
##          S22       S23       S24       S25       S26       S27       S28
## 1 1.76281735 0.1147911 0.6148642 0.3162910 0.9585927 0.5338661 0.2521686
## 2 0.27828942 1.4322639 0.5912495 0.7604426 0.3286716 0.2085977 0.5259743
## 3 0.09244458 0.1509503 0.6998436 0.3191520 0.6441894 0.5047336 0.3805181
## 4 0.25223997 0.2500180 1.8461901 0.6878982 0.3330540 0.7518151 0.3540353
## 5 2.03381243 3.4923735 0.4153228 0.1254313 0.1696408 0.9698892 2.7246227
## 6 1.48631692 7.3792361 0.6324634 0.9520021 0.9154939 0.1794937 0.3834071
##         S29 Trajectory
## 1 0.6836988   15.63293
## 2 0.3593800   14.60093
## 3 0.3359345   19.59814
## 4 0.5050881   21.38160
## 5 1.8207584   28.96757
## 6 0.9149454   42.62136</code></pre>
<p>Finally, we determine the angle (α) of consecutive trajectory segments with respect to the second axis of the 2D stable isotope space:</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Angles</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryAngles2D</a></span><span class="op">(</span><span class="va">furseals</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"d13C"</span>,<span class="st">"d15N"</span><span class="op">)</span><span class="op">]</span>,
                           <span class="va">furseals</span><span class="op">$</span><span class="va">ID_SITA</span>,
                           <span class="va">furseals</span><span class="op">$</span><span class="va">Time</span>, betweenSegments<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">Angles</span><span class="op">)</span></code></pre></div>
<pre><code>##    Axis2-t1  Axis2-t2  Axis2-t3   Axis2-t4   Axis2-t5  Axis2-t6  Axis2-t7
## 1  75.96376 161.64894 195.57662 222.448400   9.008504  48.14751  25.79603
## 2 179.32369 147.49601 315.00000 337.758643  47.109090 356.04023 139.72521
## 3 243.98585 206.02112 198.13327   1.735705 326.780524  10.11145 151.99944
## 4  64.19912  63.68191  66.46289 119.500725 237.639062 171.99527 255.90203
## 5 263.32352 271.65188 195.28972 181.584670 174.709919 343.77386  61.26355
## 6  65.68510  43.26505 163.63292  53.082435 298.712949 139.46085  99.02053
##    Axis2-t8  Axis2-t9 Axis2-t10   Axis2-t11 Axis2-t12 Axis2-t13 Axis2-t14
## 1 358.86075 283.83485 352.13745  22.5303928 192.99462 157.35838 199.76717
## 2 307.01513 171.27328 215.35767  80.5552424  19.74159  26.62133 201.67665
## 3 186.01189  37.90916  45.90222   0.7913279 198.10848 214.09786  81.85301
## 4 250.78846 351.06043  81.67311 261.0762308  90.43079  53.84926 234.02761
## 5  62.15609  60.16163  36.43393 125.7717105  83.18179 293.79978 270.44483
## 6 265.51539 245.97847 247.59927 224.5913352  66.55194  64.26158  61.40918
##   Axis2-t15 Axis2-t16 Axis2-t17 Axis2-t18 Axis2-t19 Axis2-t20 Axis2-t21
## 1 182.32153 112.32286  37.13207  351.0561 280.57797 209.98421 149.36458
## 2 203.10181 122.62605  56.38032  290.3834 341.27235 223.14352  73.85566
## 3  34.05313  18.22286 331.68664  173.8183 198.63646 223.85280 167.00538
## 4 180.47632 178.01222  48.64094  208.3422  64.39713 244.35079  38.91926
## 5 236.67073 131.62432 147.71456  228.4064 173.30874 159.83930 179.23269
## 6  52.20915 115.78169  71.69294   42.1451 219.40066  71.88535  52.22900
##   Axis2-t22 Axis2-t23 Axis2-t24 Axis2-t25 Axis2-t26 Axis2-t27 Axis2-t28
## 1 188.15309  198.2771  338.7350 109.58071 196.73359 224.92411 352.48043
## 2  48.05870  155.7613  152.8282 351.45433  23.67929 346.69657 176.51200
## 3  74.31001  150.2080  331.4941 353.34260 156.77805  68.62019 338.89763
## 4 129.36932  270.6875  251.1332 240.37909 268.96776  74.65130 298.88170
## 5 254.83630  245.0713  203.1080  35.59078 163.91542  71.91999  58.09492
## 6 231.11744  239.4211  251.8515  22.74023  21.46438 118.99260 128.75316
##   Axis2-t29
## 1  31.96985
## 2  28.77587
## 3 186.15184
## 4 235.64922
## 5  61.49251
## 6  67.77996</code></pre>
</div>
<div id="identification-and-characterization-of-trajectory-clusters" class="section level3">
<h3 class="hasAnchor">
<a href="#identification-and-characterization-of-trajectory-clusters" class="anchor"></a>3.3 Identification and characterization of trajectory clusters</h3>
<p>Here we aim to define groups of fur seals depending on the similarity of their foraging strategy. We need first to calculate distances between pairs of complete trajectories in the stable isotope space:</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">D</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span><span class="op">(</span><span class="va">furseals</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"d13C"</span>,<span class="st">"d15N"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>
<span class="va">Ds</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryDistances</a></span><span class="op">(</span><span class="va">D</span>, <span class="va">furseals</span><span class="op">$</span><span class="va">ID_SITA</span>, surveys <span class="op">=</span> <span class="cn">NULL</span>, distance.type <span class="op">=</span> <span class="st">"DSPD"</span>,
                        symmetrization <span class="op">=</span> <span class="st">"mean"</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p>Then, we can use function <code><a href="https://rdrr.io/r/stats/hclust.html">hclust()</a></code> to conduct a hierarchiacl clustering on the symmetric matrix <code>D</code>:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">colstd</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"black"</span>,<span class="st">"yellow"</span>,<span class="st">"green"</span>,<span class="st">"blue"</span>,<span class="st">"grey"</span>,<span class="st">"red"</span><span class="op">)</span>
<span class="va">pt</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16</span>,<span class="fl">16</span>,<span class="fl">16</span>,<span class="fl">16</span><span class="op">)</span>
<span class="va">hsxy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/hclust.html">hclust</a></span><span class="op">(</span><span class="va">Ds</span>, <span class="st">"ward.D2"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">hsxy</span>,hang <span class="op">=</span> <span class="op">-</span><span class="fl">1</span>, main<span class="op">=</span><span class="st">"distance Fur Seals"</span>, cex<span class="op">=</span><span class="fl">.6</span><span class="op">)</span>
<span class="va">Hst</span><span class="op">=</span><span class="fl">2</span> <span class="co"># Cutting height</span>
<span class="va">x</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/rect.hclust.html">rect.hclust</a></span><span class="op">(</span><span class="va">hsxy</span>, h<span class="op">=</span><span class="va">Hst</span>,
               border <span class="op">=</span> <span class="va">colstd</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-5-1.png" width="576"></p>
<p>We cut the dendrogram at height <code>Hst</code> to obtain a vector of cluster membership and copy it in <code>furseals</code> as a factor:</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">groups</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cutree.html">cutree</a></span><span class="op">(</span><span class="va">hsxy</span>, h<span class="op">=</span><span class="va">Hst</span><span class="op">)</span>
<span class="va">furseals</span><span class="op">$</span><span class="va">cluster</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">groups</span><span class="op">)</span></code></pre></div>
<div id="individual-trophic-trajectories-for-males-and-females-of-a--gazella-and-a--tropicalis" class="section level4">
<h4 class="hasAnchor">
<a href="#individual-trophic-trajectories-for-males-and-females-of-a--gazella-and-a--tropicalis" class="anchor"></a>3.3.1 Individual trophic trajectories for males and females of <em>A. gazella</em> and <em>A. tropicalis</em>
</h4>
<p>Here we display trophic trajectories of all individuals, in plots corresponding to combinations of species and gender. To facilitate such plots, we create of a vector with the combination of species and gender:</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">furseals</span><span class="op">$</span><span class="va">sp_gender</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">furseals</span><span class="op">$</span><span class="va">Sexe</span>, <span class="va">furseals</span><span class="op">$</span><span class="va">Species</span>, sep<span class="op">=</span><span class="st">" "</span><span class="op">)</span></code></pre></div>
<p>We now create a diagram to display fur seal trophic trajectories in the stable isotope space. Panels correspond to the combination of species and gender. In each panel, X-Y axes are defined by d13C and d15N stable isotope values. Arrows connects all whiskers section SI states from t1 to t30 (i.e. most recent to oldest SI state). Colors corresponds to trajectory clusters and shape to breeding sites:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">furseals</span>,<span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">d13C</span>,y<span class="op">=</span><span class="va">d15N</span>,color<span class="op">=</span><span class="va">cluster</span>,shape<span class="op">=</span><span class="va">Place</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">geom_path</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">d13C</span>,y<span class="op">=</span><span class="va">d15N</span>,group<span class="op">=</span><span class="va">ID_SITA</span>,color<span class="op">=</span><span class="va">cluster</span><span class="op">)</span>,arrow <span class="op">=</span> <span class="fu">arrow</span><span class="op">(</span>length <span class="op">=</span> <span class="fu">unit</span><span class="op">(</span><span class="fl">0.10</span>, <span class="st">"cm"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">xlab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">delta</span><span class="op">^</span><span class="fl">13</span><span class="op">*</span><span class="st">"C"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">ylab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">delta</span><span class="op">^</span><span class="fl">15</span><span class="op">*</span><span class="st">"N"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span><span class="va">sp_gender</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-8-1.png" width="576"></p>
</div>
<div id="net-changes-time-series-for-males-and-females-of-both-fur-seal-species" class="section level4">
<h4 class="hasAnchor">
<a href="#net-changes-time-series-for-males-and-females-of-both-fur-seal-species" class="anchor"></a>3.3.2 Net changes time series for males and females of both fur seal species</h4>
<p>In this sub-section we display net changes time series for all individuals, in plots corresponding to combinations of species and gender We prepare a subset of the data called <code>NC</code>:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">NC</span><span class="op">&lt;-</span><span class="va">Net_changes</span><span class="op">[</span>,<span class="op">-</span><span class="fl">30</span><span class="op">]</span>
<span class="va">NC</span><span class="op">$</span><span class="va">cluster</span><span class="op">&lt;-</span><span class="va">furseals</span><span class="op">$</span><span class="va">cluster</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">47</span><span class="op">]</span>
<span class="va">NC</span><span class="op">$</span><span class="va">ID</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">NC</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">NC</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span><span class="op">:</span><span class="fl">30</span>,<span class="st">"cluster"</span>,<span class="st">"ID"</span><span class="op">)</span></code></pre></div>
<p>We then prepare the subset. We notably transform NC in a line structure to compute <code>NCline</code> using the function “melt”, order the data set and add the vector sp_gender:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">NCline</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu">melt</span><span class="op">(</span><span class="va">NC</span>,id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ID"</span>,<span class="st">"cluster"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">NCline</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ID"</span>,<span class="st">"Clusters"</span>,<span class="st">"Time_from_present"</span>,<span class="st">"Net_changes"</span><span class="op">)</span>
<span class="va">NCline</span><span class="op">[</span>,<span class="fl">3</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">NCline</span><span class="op">[</span>,<span class="fl">3</span><span class="op">]</span><span class="op">)</span>
<span class="va">NCline</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">NCline</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span>
<span class="va">NCline</span><span class="op">&lt;-</span><span class="va">NCline</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">NCline</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>,decreasing<span class="op">=</span><span class="cn">F</span><span class="op">)</span>, <span class="op">]</span></code></pre></div>
<pre><code>## Warning in xtfrm.data.frame(x): cannot xtfrm data frames</code></pre>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">NCline</span><span class="op">$</span><span class="va">sp_gender</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">furseals</span><span class="op">$</span><span class="va">sp_gender</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">47</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<p>We now create the plot to display net changes time series for all individuals in panel corresponding Arrows connects all whiskers section stable isotope values from t1 to t30 (i.e. most recent to oldest stable isotope values). Colours corresponds to trajectory clusters:</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">NCline</span>,<span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">Time_from_present</span>,y<span class="op">=</span><span class="va">Net_changes</span>,color<span class="op">=</span><span class="va">Clusters</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">geom_path</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">Time_from_present</span>,y<span class="op">=</span><span class="va">Net_changes</span>,group<span class="op">=</span><span class="va">ID</span>,color<span class="op">=</span><span class="va">Clusters</span><span class="op">)</span>,arrow <span class="op">=</span> <span class="fu">arrow</span><span class="op">(</span>length <span class="op">=</span> <span class="fu">unit</span><span class="op">(</span><span class="fl">0.10</span>, <span class="st">"cm"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span><span class="va">sp_gender</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-11-1.png" width="576"></p>
</div>
<div id="angle-α-trajectory-roses-of-fur-seals-trajectory-cluster-" class="section level4">
<h4 class="hasAnchor">
<a href="#angle-%CE%B1-trajectory-roses-of-fur-seals-trajectory-cluster-" class="anchor"></a>3.3.3 Angle α trajectory roses of Fur seals trajectory cluster.</h4>
<p>In this sub-section, we plot the distribution of Angle α values in a trajectory rose<br>
We prepare the data set to compute the trajectoy rose and transform it in a line structure. We create a vector of direction to class Angle α values by range of 15°:</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Angl</span><span class="op">&lt;-</span><span class="va">Angles</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">Angl</span><span class="op">)</span><span class="op">&lt;-</span><span class="fl">2</span><span class="op">:</span><span class="fl">30</span>
<span class="va">Angl</span><span class="op">$</span><span class="va">ID</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">Angl</span><span class="op">)</span><span class="op">)</span>
<span class="va">Angl</span><span class="op">$</span><span class="va">cluster</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">groups</span><span class="op">)</span>
<span class="va">Angl</span><span class="op">$</span><span class="va">sp_gender</span><span class="op">&lt;-</span><span class="va">furseals</span><span class="op">$</span><span class="va">sp_gender</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">47</span><span class="op">]</span>
<span class="va">Angline</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu">melt</span><span class="op">(</span><span class="va">Angl</span>,id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ID"</span>,<span class="st">"cluster"</span>,<span class="st">"sp_gender"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">Angline</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ID"</span>,<span class="st">"Clusters"</span>,<span class="st">"Group"</span>,<span class="st">"Time_from_present"</span>,<span class="st">"Direction"</span><span class="op">)</span>
<span class="va">Angline</span><span class="op">$</span><span class="va">Direction</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">Angline</span><span class="op">$</span><span class="va">Direction</span><span class="op">)</span>


<span class="co"># range 15°</span>
<span class="va">deg</span> <span class="op">&lt;-</span> <span class="fl">15</span>
<span class="co"># vector for range of direction of differents bars</span>
<span class="va">dir.breaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span><span class="op">-</span><span class="op">(</span><span class="va">deg</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span>, <span class="fl">360</span><span class="op">+</span><span class="op">(</span><span class="va">deg</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span>, <span class="va">deg</span><span class="op">)</span>
<span class="va">dir.binned</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">Angline</span><span class="op">$</span><span class="va">Direction</span>,
                  breaks <span class="op">=</span> <span class="va">dir.breaks</span>,
                  ordered_result <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co"># direction labels</span>
<span class="va">dir.labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">360</span><span class="op">-</span><span class="va">deg</span>, by <span class="op">=</span> <span class="va">deg</span><span class="op">)</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dir.binned</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">dir.labels</span>

<span class="co"># angles distribution in each range of direction</span>
<span class="va">Angline</span><span class="op">$</span><span class="va">dir.binned</span> <span class="op">&lt;-</span> <span class="va">dir.binned</span>

<span class="co"># sort angles</span>
<span class="va">df_sorted</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">Angline</span><span class="op">$</span><span class="va">dir.binned</span>, <span class="va">Angline</span><span class="op">$</span><span class="va">Clusters</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df_sorted</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dir.binned"</span>,<span class="st">"Clusters"</span>,<span class="st">"nb"</span><span class="op">)</span>

<span class="va">df_cumsum</span> <span class="op">&lt;-</span> <span class="fu">ddply</span><span class="op">(</span><span class="va">df_sorted</span>, <span class="st">"dir.binned"</span>,
                   <span class="va">transform</span>, label_ypos<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">nb</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>We now create the trajectory rose. Angles α were calculated in 2D Ωδ space (δ 13C/δ 15N) and represented by range (15°) of direction. Bars size represent the number of trajectory segments (all individual within each trajectory clusters).</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">df_cumsum</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">dir.binned</span>, y<span class="op">=</span><span class="va">nb</span>, fill<span class="op">=</span><span class="va">Clusters</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_bar</span><span class="op">(</span>stat<span class="op">=</span><span class="st">"identity"</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">scale_y_continuous</span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">110</span><span class="op">)</span>, expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span>, 
                     breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">25</span>,<span class="fl">50</span>,<span class="fl">75</span>,<span class="fl">110</span><span class="op">)</span>, 
                     labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">25</span>,<span class="fl">50</span>,<span class="fl">75</span>,<span class="fl">110</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Trajectory segment directions within fur seals clusters'</span>, y <span class="op">=</span> <span class="st">'number of trajectory segments'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">coord_polar</span><span class="op">(</span>start <span class="op">=</span> <span class="op">-</span><span class="op">(</span><span class="va">deg</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-13-1.png" width="576"></p>
</div>
</div>
</div>
<div id="ontogenic-stable-isotope-trajectories-of-juvenile-fishes" class="section level2">
<h2 class="hasAnchor">
<a href="#ontogenic-stable-isotope-trajectories-of-juvenile-fishes" class="anchor"></a>4. Ontogenic stable isotope trajectories of juvenile fishes</h2>
<p>In this section, we illustrate how to calculate trajectory metrics to characterize the ontogenic stable isotope trajectories of juvenile fishes. In the following sections, we show how to use these metrics as data to create a trajectory diagram.</p>
<div id="loading-data" class="section level3">
<h3 class="hasAnchor">
<a href="#loading-data" class="anchor"></a>4.1 Loading data</h3>
<p>We begin by loading the package dataset <code>pike</code>:</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"pike"</span><span class="op">)</span></code></pre></div>
<p>This is a data set from :</p>
<ul>
<li>Cucherousset, J., Paillisson, J.-M., Roussel, J.-M., 2013. Natal departure timing from spatially varying environments is dependent of individual ontogenetic status. <em>Naturwissenschaften</em> 100, 761–768.</li>
</ul>
<p>Briefly, Cucherousset et al. (2013) released 192 individually tagged, hatchery-raised, juvenile pike (<em>Esox lucius</em> L.) with variable initial trophic position (fin δ13C/δ15N values). Based on δ15N values, individuals were classified into zooplanktivorous (δ15N &lt; 10 ‰) and piscivorous (δ15N &gt; 10 ‰) as cannibalism is commonly observed in this species. Individuals were released in a temporarily flooded grassland where pike eggs usually hatch of the Brière marsh (France) to identify the determinants of juvenile natal departure. The release site was connected through a unique point to an adjacent pond used as a nursery habitat. Fish were continuously recaptured when migrating from flooded grassland to adjacent pond. Recaptured individuals (n = 29) were anaesthetized, checked for tags, measured for fork length, fin-clipped to quantify changes in δ13C and δ15N values, and released.</p>
</div>
<div id="calculating-trajectory-metrics-and-identification-of-trajectory-clusters" class="section level3">
<h3 class="hasAnchor">
<a href="#calculating-trajectory-metrics-and-identification-of-trajectory-clusters" class="anchor"></a>4.2 Calculating trajectory metrics and identification of trajectory clusters</h3>
<p>First, we calculate net changes relative to the initial state for each individual (i.e. the distance between stable isotope compositions at release and at recapture):</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Net_changes</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryLengths2D</a></span><span class="op">(</span><span class="va">pike</span><span class="op">[</span>,<span class="fl">7</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span>,<span class="va">pike</span><span class="op">$</span><span class="va">ID</span>,<span class="va">pike</span><span class="op">$</span><span class="va">Time</span>, relativeToInitial<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span> 
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">Net_changes</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Net_changes"</span>, <span class="st">"Trajectory"</span><span class="op">)</span>
<span class="va">pike</span><span class="op">$</span><span class="va">Net_Changes</span><span class="op">&lt;-</span><span class="va">Net_changes</span><span class="op">$</span><span class="va">Net_changes</span></code></pre></div>
<p>Then, we can use function <code><a href="https://rdrr.io/r/stats/hclust.html">hclust()</a></code> to conduct a hierarchiacl clustering on the symmetric matrix <code>D</code>:</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">D</span><span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span><span class="op">(</span><span class="va">pike</span><span class="op">[</span>,<span class="fl">7</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span><span class="op">)</span>
<span class="va">Ds</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryDistances</a></span><span class="op">(</span><span class="va">D</span>,<span class="va">pike</span><span class="op">$</span><span class="va">ID</span>, surveys <span class="op">=</span> <span class="cn">NULL</span>, distance.type <span class="op">=</span> <span class="st">"DSPD"</span>,
                        symmetrization <span class="op">=</span> <span class="st">"mean"</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p>We cut the dendrogram at height <code>Hst</code> to obtain a vector of cluster membership and copy it in <code>pike</code>:</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Hst</span><span class="op">=</span><span class="fl">3</span>
<span class="va">colstd</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"black"</span>,<span class="st">"yellow"</span>,<span class="st">"green"</span>,<span class="st">"blue"</span>,<span class="st">"grey"</span>,<span class="st">"red"</span><span class="op">)</span>
<span class="va">hsxy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/hclust.html">hclust</a></span><span class="op">(</span><span class="va">Ds</span>, <span class="st">"ward.D2"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">hsxy</span>,hang <span class="op">=</span> <span class="op">-</span><span class="fl">1</span>, main<span class="op">=</span><span class="st">"distance Pike"</span>, cex<span class="op">=</span><span class="fl">.6</span><span class="op">)</span>
<span class="va">x</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/rect.hclust.html">rect.hclust</a></span> <span class="op">(</span><span class="va">hsxy</span>, h<span class="op">=</span><span class="va">Hst</span>,
                border <span class="op">=</span> <span class="va">colstd</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-16-1.png" width="576"></p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Store clusters into a new data column</span>
<span class="va">pike</span><span class="op">$</span><span class="va">Cluster</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/cutree.html">cutree</a></span><span class="op">(</span><span class="va">hsxy</span>, h<span class="op">=</span><span class="va">Hst</span><span class="op">)</span></code></pre></div>
</div>
<div id="trajectory-diagram-of-pike-released-in-the-flooded-grassland-and-recaptured-when-emigrating-into-the-adjacent-pond" class="section level3">
<h3 class="hasAnchor">
<a href="#trajectory-diagram-of-pike-released-in-the-flooded-grassland-and-recaptured-when-emigrating-into-the-adjacent-pond" class="anchor"></a>4.3 Trajectory diagram of pike released in the flooded grassland and recaptured when emigrating into the adjacent pond</h3>
<p>We prepare the data set to compute trajectory diagrams and density curves:</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Pike1</span><span class="op">&lt;-</span><span class="va">pike</span><span class="op">[</span><span class="va">pike</span><span class="op">$</span><span class="va">Time</span> <span class="op">%in%</span> <span class="fl">1</span>,<span class="op">]</span>
<span class="va">Pike1</span><span class="op">&lt;-</span><span class="va">Pike1</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">Pike1</span><span class="op">$</span><span class="va">ID</span>, decreasing<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>,<span class="op">]</span>
<span class="va">Pike1</span><span class="op">$</span><span class="va">Net_changes</span><span class="op">&lt;-</span><span class="fl">0</span>
<span class="va">Pike2</span><span class="op">&lt;-</span><span class="va">pike</span><span class="op">[</span><span class="va">pike</span><span class="op">$</span><span class="va">Time</span> <span class="op">%in%</span> <span class="fl">2</span>,<span class="op">]</span>
<span class="va">Pike2</span><span class="op">&lt;-</span><span class="va">Pike2</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">Pike2</span><span class="op">$</span><span class="va">ID</span>, decreasing<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>,<span class="op">]</span>
<span class="va">Pike2</span><span class="op">$</span><span class="va">Net_changes</span><span class="op">&lt;-</span><span class="va">Net_changes</span><span class="op">$</span><span class="va">Net_changes</span>
<span class="va">data</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">Pike1</span>,<span class="va">Pike2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>We create the trajectory diagram. Arrows represent trajectory path for each pit-tagged individual. Colors correspond to trajectory clusters. The dashed line separates piscivorous from zooplanktivorous individuals [zooplanktivorous (δ15N &lt; 10) vs piscivorous (δ15N &gt; 10)].</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data</span>,<span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">d13C</span>,y<span class="op">=</span><span class="va">d15N</span>,shape<span class="op">=</span><span class="va">Trophic_status_initial</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>size<span class="op">=</span><span class="va">Net_changes</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">geom_path</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">d13C</span>,y<span class="op">=</span><span class="va">d15N</span>,group<span class="op">=</span><span class="va">ID</span>,color<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Cluster</span><span class="op">)</span><span class="op">)</span>,arrow <span class="op">=</span> <span class="fu">arrow</span><span class="op">(</span>length <span class="op">=</span> <span class="fu">unit</span><span class="op">(</span><span class="fl">0.30</span>, <span class="st">"cm"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">10</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">xlab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">delta</span><span class="op">^</span><span class="fl">13</span><span class="op">*</span><span class="st">"C"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ylab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">delta</span><span class="op">^</span><span class="fl">15</span><span class="op">*</span><span class="st">"N"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-18-1.png" width="576"></p>
<p>Density curves X represents the distribution of all samples according to δ13C values, and capture (green=release; red=departure):</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">gg_dist_d13C</span> <span class="op">=</span> <span class="fu">ggplot</span><span class="op">(</span><span class="va">data</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">d13C</span>, fill<span class="op">=</span><span class="va">TimeL</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">geom_density</span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">.5</span><span class="op">)</span> 
<span class="va">gg_dist_d13C</span> <span class="op">=</span> <span class="va">gg_dist_d13C</span> <span class="op">+</span> <span class="fu">ylab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">delta</span><span class="op">^</span><span class="fl">13</span><span class="op">*</span><span class="st">"C"</span><span class="op">*</span><span class="st">" density"</span><span class="op">)</span><span class="op">)</span>
<span class="va">gg_dist_d13C</span> <span class="op">=</span> <span class="va">gg_dist_d13C</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>axis.title.y<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                    axis.text<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                    axis.line<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                    axis.ticks<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                    panel.grid.major <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                    panel.grid.minor <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                    panel.background <span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span>
<span class="va">gg_dist_d13C</span> <span class="op">=</span> <span class="va">gg_dist_d13C</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span>
<span class="va">gg_dist_d13C</span> <span class="op">+</span> <span class="fu">scale_x_continuous</span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">33</span>, <span class="op">-</span><span class="fl">25</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu">scale_y_continuous</span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-19-1.png" width="384"></p>
<p>Density curves Y represents the distribution of all samples according to δ15N values, and capture (green=release; red=departure):</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">gg_dist_d15N</span> <span class="op">=</span> <span class="fu">ggplot</span><span class="op">(</span><span class="va">data</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">d15N</span>, fill<span class="op">=</span><span class="va">TimeL</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">geom_density</span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">.5</span><span class="op">)</span> 
<span class="va">gg_dist_d15N</span> <span class="op">=</span> <span class="va">gg_dist_d15N</span> <span class="op">+</span> <span class="fu">ylab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">delta</span><span class="op">^</span><span class="fl">15</span><span class="op">*</span><span class="st">"N"</span><span class="op">*</span><span class="st">" density"</span><span class="op">)</span><span class="op">)</span>
<span class="va">gg_dist_d15N</span> <span class="op">=</span><span class="va">gg_dist_d15N</span> 
<span class="va">gg_dist_d15N</span> <span class="op">=</span><span class="va">gg_dist_d15N</span> <span class="op">+</span> <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span>
<span class="va">gg_dist_d15N</span> <span class="op">=</span><span class="va">gg_dist_d15N</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>axis.title.y<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                   axis.text<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                   axis.line<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                   axis.ticks<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                   panel.grid.major <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                   panel.grid.minor <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
                                   panel.background <span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span>
<span class="va">gg_dist_d15N</span> <span class="op">=</span><span class="va">gg_dist_d15N</span> <span class="op">+</span><span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span>
<span class="va">gg_dist_d15N</span> <span class="op">+</span> <span class="fu">scale_x_continuous</span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>, <span class="fl">14</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu">scale_y_continuous</span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-20-1.png" width="384"></p>
</div>
</div>
<div id="spatio-temporal-variability-of-δ13c-and-δ15n-modelled-isoscapes-in-the-northeast-pacific" class="section level2">
<h2 class="hasAnchor">
<a href="#spatio-temporal-variability-of-%CE%B413c-and-%CE%B415n-modelled-isoscapes-in-the-northeast-pacific" class="anchor"></a>5. Spatio-temporal variability of δ13C and δ15N modelled isoscapes in the Northeast Pacific</h2>
<p>In this section, we illustrate how to use trajectory metrics to characterize the spatio-temporal variability of δ13C and δ15N modelled isoscapes in the Northeast Pacific in an isoscape trajectory map and a trajectory heat map</p>
<p>The datasets used in this application come from:</p>
<ul>
<li>Espinasse, B., Hunt, B.P.V., Batten, S.D., Pakhomov, E.A., 2020. Defining isoscapes in the Northeast Pacific as an index of ocean productivity. Global Ecol Biogeogr 29, 246–261.</li>
</ul>
<p>Briefly, Espinasse et al. (2020) tested the application of isoscapes modelled from satellite data to the description of secondary production in the Northeast pacific. The output model fits in a 0.25° x 0.25° spatial grid covering the region spanning from 46 to 62°N and from 195 to 235°E and supporting δ13C and δ15N isoscapes from 1998 to 2017. We subset modelled δ13C and δ15N values of a 1° x 1° spatial grid from the original modelled dataset. Isoscapes modelled for 2013, 2015 and 2017 were selected as they were characterised by high stable isotope dynamics and consequently constitutes relevant inputs to test our isoscape trajectory map concept. Additionally, a long-term SITA analysis was performed from 1998 to 2017 using directions and net changes calculated for all pairs of dates (1998-1999,… ,2016-2017) as input for a trajectory heat map.</p>
<div id="isoscape-trajectory-maps" class="section level3">
<h3 class="hasAnchor">
<a href="#isoscape-trajectory-maps" class="anchor"></a>5.1 2013-2015 Isoscape trajectory maps</h3>
<p>We begin by loading the package dataset <code>isoscape</code>:</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"isoscape"</span><span class="op">)</span></code></pre></div>
<p>We calculate Segment lengths and Angle α for each stations to assess, respectively, the magnitude and the nature of change in the stable isotope space between 2013 and 2015. We then prepare a data set to compute the isoscape trajectory map with notably: Latitude, Longitude, Years, Angles and segment lenghts values:</p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sites</span><span class="op">&lt;-</span><span class="va">isoscape</span><span class="op">$</span><span class="va">station</span>
<span class="va">surveys</span><span class="op">&lt;-</span><span class="va">isoscape</span><span class="op">$</span><span class="va">Year</span>
<span class="va">Angl</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryAngles2D</a></span><span class="op">(</span><span class="va">isoscape</span><span class="op">[</span>,<span class="fl">3</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span>,<span class="va">sites</span>,<span class="va">surveys</span>, betweenSegments <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">Length</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/trajectorymetrics.html">trajectoryLengths2D</a></span><span class="op">(</span><span class="va">isoscape</span><span class="op">[</span>,<span class="fl">3</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span>,<span class="va">sites</span>,<span class="va">surveys</span><span class="op">)</span>
<span class="va">data</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">isoscape</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">489</span>,<span class="op">]</span>,<span class="va">Angl</span>,<span class="va">Length</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Latitude"</span>,<span class="st">"Longitude"</span>,<span class="st">"d13C"</span>,<span class="st">"d15N"</span>,<span class="st">"Stations"</span>,<span class="st">"Years"</span>,<span class="st">"Angles"</span>,<span class="st">"Lengths"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></code></pre></div>
<pre><code>##   Latitude Longitude      d13C     d15N Stations Years    Angles    Lengths
## 1       46       195 -24.24369 5.267485        1  2013 210.45063 0.31556226
## 2       48       195 -24.32212 4.973764        3  2013 279.70681 0.28077863
## 3       49       195 -24.28151 5.113458        4  2013 188.55168 0.03490337
## 4       50       195 -24.30105 5.261582        5  2013 147.84429 0.25570108
## 5       51       195 -24.05084 5.302065        6  2013 126.14883 0.32439073
## 6       52       195 -23.92968 5.407169        7  2013  60.21061 0.28423495</code></pre>
<p>Angles α need to be transformed for the use with <code>geom_spoke</code>. We then add transformed values in a new column <code>Angles2</code>.</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">angle</span><span class="op">&lt;-</span><span class="va">data</span><span class="op">$</span><span class="va">Angles</span>
<span class="va">Angles2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">)</span>
<span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">angle</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">Angles2</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">==</span><span class="fl">0</span>,<span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">-</span><span class="fl">270</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                         <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">==</span><span class="fl">180</span>,<span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">-</span><span class="fl">270</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                                <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">==</span><span class="fl">90</span>,<span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">+</span><span class="fl">270</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                                       <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">==</span><span class="fl">270</span>,<span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">+</span><span class="fl">270</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                                              <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">==</span><span class="fl">360</span>,<span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">-</span><span class="fl">270</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,  
                                                     <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&gt;</span><span class="fl">0</span> <span class="op">&amp;</span> <span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;</span><span class="fl">90</span> ,<span class="op">(</span><span class="fl">90</span><span class="op">-</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                                                            <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&gt;</span><span class="fl">90</span> <span class="op">&amp;</span> <span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;</span><span class="fl">180</span> ,<span class="op">(</span><span class="fl">90</span><span class="op">-</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                                                                   <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&gt;</span><span class="fl">180</span> <span class="op">&amp;</span> <span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;</span><span class="fl">270</span>,<span class="op">(</span><span class="fl">180</span><span class="op">+</span><span class="op">(</span><span class="fl">270</span><span class="op">-</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,
                                                                          <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&gt;</span><span class="fl">270</span> <span class="op">&amp;</span> <span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;</span><span class="fl">360</span>,<span class="op">(</span><span class="fl">90</span><span class="op">+</span><span class="op">(</span><span class="fl">360</span><span class="op">-</span><span class="va">angle</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="va">pi</span><span class="op">/</span><span class="fl">180</span>,<span class="st">"ERROR"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span>

<span class="va">data</span><span class="op">$</span><span class="va">Angles2</span><span class="op">&lt;-</span><span class="va">Angles2</span></code></pre></div>
<p>We now create the Isoscape trajectory map. In this kind of map, Segment lengths and Angle α are mapped to illustrate stable isotope spatio-temporal dynamics. Direction of arrows (angle α) illustrate direction (i.e. the nature of change) in the modelled 2D Ωδ space according to increase and/or decrease in δ13C and δ15N values (0-90°: + δ13C and + δ15N; 90-180°: + δ13C and - δ15N; 90-180°: + δ13C and - δ15N; 180-270°: + δ13C and - δ15N). Length of arrows and colored background rasters illustrate modelled trajectory segment length at each station (i.e. the magnitude of change).</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">data</span>, 
          <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Longitude</span>, 
              y <span class="op">=</span> <span class="va">Latitude</span>, 
              fill <span class="op">=</span> <span class="va">Lengths</span>, 
              angle <span class="op">=</span> <span class="va">Angles2</span>, 
              radius <span class="op">=</span> <span class="fu">rescale</span><span class="op">(</span><span class="va">Lengths</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.3</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_raster</span><span class="op">(</span>interpolate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_spoke</span><span class="op">(</span>arrow <span class="op">=</span> <span class="fu">arrow</span><span class="op">(</span>length <span class="op">=</span> <span class="fu">unit</span><span class="op">(</span><span class="fl">.07</span>, <span class="st">'inches'</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">scale_fill_distiller</span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"RdYlBu"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">coord_equal</span><span class="op">(</span>expand <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">'bottom'</span>, 
        legend.direction <span class="op">=</span> <span class="st">'horizontal'</span>,
        panel.background <span class="op">=</span> <span class="fu">element_rect</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-23-1.png" width="576"></p>
</div>
<div id="trajectory-heatmap" class="section level3">
<h3 class="hasAnchor">
<a href="#trajectory-heatmap" class="anchor"></a>5.2 1998-2017 trajectory heatmap</h3>
<p>We begin by loading the package dataset <code>heatmapdata</code>:</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"heatmapdata"</span><span class="op">)</span></code></pre></div>
<p><code>heatmapdata</code> is composed of trajectory metrics for all stations within all inter-annual consecutive periods between 1998 and 2017:</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">heatmapdata</span><span class="op">)</span></code></pre></div>
<pre><code>##   Latitude Longitude      d13C     d15N Stations     Years    Angles    Lengths
## 1       46       195 -24.76366 5.451872        1 1998-1999 181.31874 0.30196921
## 2       47       195 -24.75540 5.334980        2 1998-1999 213.76898 0.09285079
## 3       48       195 -24.51122 5.382608        3 1998-1999 183.00600 0.24017740
## 4       49       195 -24.46314 5.481623        4 1998-1999 169.30735 0.34248078
## 5       50       195 -24.27419 5.893179        5 1998-1999 174.57293 0.81250282
## 6       51       195 -24.19454 5.780701        6 1998-1999  13.28445 0.96866737
##     Angles2
## 1  4.689373
## 2  4.123009
## 3  4.659924
## 4 -1.384174
## 5 -1.476076
## 6  1.338939</code></pre>
<p>We then prepare the data set to create the trajectory heat map. We create a vector of direction, ranging by 15° between 0 and 360°, to class Angle α values. We create the vector <code>ISPattern</code> to characterize the pattern of direction according to changes in both stable isotope values (0-90°: + δ13C and + δ15N; 90-180°: + δ13C and - δ15N; 90-180°: + δ13C and - δ15N; 180-270°: + δ13C and - δ15N):</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#direction range</span>
<span class="va">deg</span> <span class="op">&lt;-</span> <span class="fl">15</span>

<span class="va">dir.breaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">15</span>,<span class="fl">30</span>,<span class="fl">45</span>,<span class="fl">60</span>,<span class="fl">75</span>,<span class="fl">90</span>,<span class="fl">105</span>,<span class="fl">120</span>,<span class="fl">135</span>,<span class="fl">150</span>,<span class="fl">165</span>,<span class="fl">180</span>,<span class="fl">195</span>,<span class="fl">210</span>,<span class="fl">225</span>,<span class="fl">240</span>,<span class="fl">255</span>,<span class="fl">270</span>,<span class="fl">285</span>,<span class="fl">300</span>,<span class="fl">315</span>,<span class="fl">330</span>,<span class="fl">345</span>,<span class="fl">360</span><span class="op">)</span>


<span class="va">dir.binned</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">heatmapdata</span><span class="op">$</span><span class="va">Angles</span>,
                  breaks <span class="op">=</span> <span class="va">dir.breaks</span>,
                  ordered_result <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="co"># bar labels</span>
<span class="va">dir.labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">360</span><span class="op">-</span><span class="va">deg</span>, by <span class="op">=</span> <span class="va">deg</span><span class="op">)</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dir.binned</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">dir.labels</span>

<span class="va">heatmapdata</span><span class="op">$</span><span class="va">dir.binned</span> <span class="op">&lt;-</span> <span class="va">dir.binned</span>

<span class="va">data</span><span class="op">&lt;-</span><span class="va">heatmapdata</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6</span>,<span class="fl">7</span>,<span class="fl">8</span>,<span class="fl">10</span><span class="op">)</span><span class="op">]</span>

<span class="co">#direction vs SI patterns</span>
<span class="va">data</span><span class="op">&lt;-</span><span class="va">data</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">dir.binned</span>, decreasing<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>,<span class="op">]</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">&lt;-</span><span class="fl">1</span><span class="op">:</span><span class="fl">9206</span>
<span class="va">data</span><span class="op">$</span><span class="va">ISpattern</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"+d13C/+d15N"</span>,<span class="fl">2862</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"+d13C/-d15N"</span>,<span class="fl">1840</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"-d13C/-d15N"</span>,<span class="fl">2931</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"-d13C/+d15N"</span>,<span class="fl">1573</span><span class="op">)</span><span class="op">)</span>

<span class="va">data1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">dir.binned</span>,<span class="va">data</span><span class="op">$</span><span class="va">Years</span><span class="op">)</span><span class="op">)</span>

<span class="va">data2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">data</span><span class="op">$</span><span class="va">Lengths</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">dir.binned</span>, <span class="va">data</span><span class="op">$</span><span class="va">Years</span><span class="op">)</span>, FUN<span class="op">=</span><span class="va">sum</span>, drop<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>
<span class="va">data2</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">data2</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">0</span> 


<span class="va">data1</span><span class="op">$</span><span class="va">Lengths</span><span class="op">&lt;-</span><span class="va">data2</span><span class="op">$</span><span class="va">x</span>
<span class="va">dfa</span><span class="op">&lt;-</span><span class="va">data1</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">dfa</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Directions"</span>,<span class="st">"Periods"</span>,<span class="st">"Nb_stations"</span>,<span class="st">"Lengths"</span><span class="op">)</span></code></pre></div>
<p>The final dataset used to create the trajectory heat map is composed of four variables (“Directions”,“Periods”,“Nb_stations”,“Lengths”):</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dfa</span><span class="op">)</span></code></pre></div>
<pre><code>##   Directions   Periods Nb_stations   Lengths
## 1          0 1998-1999          12  8.634497
## 2         15 1998-1999           9 11.096406
## 3         30 1998-1999           7  7.927697
## 4         45 1998-1999           8 11.138909
## 5         60 1998-1999           4  1.861980
## 6         75 1998-1999           4  1.835733</code></pre>
<p>We plot trajectory metrics with respect to period and direction in a trajectory heat map. Angles α in the modelled 2D Ωδ space exhibited by all stations within all pairs of dates (1998-1999,…,2016-2017) are represented by range of direction (15°) according to period. Color gradient from dark blue to yellow indicate the number of stations exhibited by a given range of direction within a given period.</p>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">dfa</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">Periods</span>, <span class="va">Directions</span>, fill<span class="op">=</span> <span class="va">Nb_stations</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_tile</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_fill_viridis</span><span class="op">(</span>discrete<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span><span class="op">+</span>
  <span class="fu">theme</span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size<span class="op">=</span><span class="fl">10</span>, angle<span class="op">=</span><span class="fl">90</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-27-1.png" width="576"></p>
<p>The X bar plot represents the sum of segment lengths across stations and times, 1231 exhibiting the chosen angle. The blue gradient indicates the net change magnitude.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.Xbarplot</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">dfa</span><span class="op">$</span><span class="va">Lengths</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">dfa</span><span class="op">$</span><span class="va">Periods</span><span class="op">)</span>, FUN <span class="op">=</span> <span class="va">sum</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df.Xbarplot</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Periods"</span>,<span class="st">"Lengths"</span><span class="op">)</span>
<span class="va">bp.x</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.Xbarplot</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Periods</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">Lengths</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_bar</span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"identity"</span>, <span class="fu">aes</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">Lengths</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme</span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">10</span>,angle<span class="op">=</span><span class="fl">90</span><span class="op">)</span>, 
        axis.title.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">20</span>, margin <span class="op">=</span> <span class="fu">margin</span><span class="op">(</span><span class="fl">10</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Periods"</span><span class="op">)</span>
<span class="va">bp.x</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-28-1.png" width="480"></p>
<p>The Y bar plot represents the overall net changes according to range of directions (angle α). Bars are colored according to increase and/or decrease in δ13C and δ15N values (Pink: 0-90°: + δ13C and + δ15N ; Blue: 90-180°: + δ13C and - δ15N; Red: 90-180°: + δ13C and - δ15N; Green: 180-270°: + δ13C and - δ15N).</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.Ybarplot</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">dfa</span><span class="op">$</span><span class="va">Lengths</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">dfa</span><span class="op">$</span><span class="va">Directions</span><span class="op">)</span>, FUN <span class="op">=</span> <span class="va">sum</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df.Ybarplot</span><span class="op">)</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Directions"</span>,<span class="st">"Lengths"</span><span class="op">)</span>
<span class="va">df.Ybarplot</span><span class="op">$</span><span class="va">ISpattern</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"+d13C/+d15N"</span>,<span class="fl">6</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"+d13C/-d15N"</span>,<span class="fl">6</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"-d13C/-d15N"</span>,<span class="fl">6</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"-d13C/+d15N"</span>,<span class="fl">6</span><span class="op">)</span><span class="op">)</span>


<span class="va">bp.y</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.Ybarplot</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Directions</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">Lengths</span>,fill <span class="op">=</span> <span class="va">ISpattern</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_bar</span><span class="op">(</span>stat<span class="op">=</span><span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span>
<span class="va">bp.y</span></code></pre></div>
<p><img src="SITA_files/figure-html/unnamed-chunk-29-1.png" width="384"></p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Miquel De Cáceres, Anthony Sturbois.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
